name: CI

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '20 16 * * *'

# Set a new GitHub Actions Secret named IAR_LMS_BEARER_TOKEN
# for your repository. The secret is then propagated to an
# Environment variable used for all jobs within this workflow
env:
  IAR_LMS_BEARER_TOKEN: ${{ secrets.IAR_LMS_BEARER_TOKEN }}

jobs:
  tutorial:
    name: Build tutorial
    runs-on: ubuntu-24.04
    container: ghcr.io/iarsystems/arm
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read
    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: CMake - Configure
      working-directory: tutorial
      run: cmake -GNinja -Bbuild

    - name: CMake - Build
      working-directory: tutorial
      run: cmake --build build --verbose

    - name: IAR C-STAT Static Analysis
      working-directory: tutorial
      run: |
        ichecks --all --output build/checks.manifest
        icstat --checks build/checks.manifest --db build/cstat.db --sarif_dir build analyze -- iccarm tutorial.c
    
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: tutorial/build/tutorial.c.sarif
        category: cstat-analysis
