name: CI

on:
  push:
    paths-ignore: 
    - 'README.md'
  workflow_dispatch:
  schedule:
  - cron: '20 16 * * *'

# Set a new GitHub Actions Secret named IAR_LMS_BEARER_TOKEN
# for your repository. The secret is then propagated to an
# Environment variable used for all jobs within this workflow
env:
  IAR_LMS_BEARER_TOKEN: ${{ secrets.IAR_LMS_BEARER_TOKEN }}

# Set default permissions for the workflow jobs
permissions:
  contents: read

jobs:
  tutorial:
    name: Build tutorial
    runs-on: ubuntu-24.04
    container: ghcr.io/iarsystems/arm
    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: CMake - Configure
      working-directory: tutorial
      run: cmake -GNinja -Bbuild

    - name: CMake - Build
      working-directory: tutorial
      run: cmake --build build --verbose
